Moved from __future__ line closer to the top of the file to prevent
  File "piped.py", line 7
    from __future__ import with_statement
SyntaxError: from __future__ imports must occur at the beginning of the file